# Generated by Django 5.0.4 on 2024-04-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('ZipCode', models.IntegerField(primary_key=True, serialize=False)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ZIPCODE',
                'managed': False,
            },
        ),
    ]
