# Generated by Django 5.0.4 on 2024-04-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Patient_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50, null=True)),
                ('Last_Name', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Gender', models.CharField(max_length=1, null=True)),
                ('Address', models.CharField(max_length=50, null=True)),
                ('Phone_Number', models.CharField(max_length=15, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Patient',
                'managed': False,
            },
        ),
    ]
