# Generated by Django 5.0.4 on 2024-04-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('Allergy_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Medication', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Allergy',
                'managed': False,
            },
        ),
    ]
